---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 10-demo-kustomization-oci-dx-game-app
  namespace: flux-system
spec:
  interval: 10s
  path: ./
  prune: false
  sourceRef:
    kind: OCIRepository
    name: 10-demo-source-oci-dx-game-app
  targetNamespace: 10-demo
