---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 4-demo-kustomization-minio-s3-bucket-bx-game-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./app-78
  prune: true
  sourceRef:
    kind: Bucket
    name: 4-demo-source-minio-s3-bucket-bx-game-app
  targetNamespace: 4-demo
