---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 5-demo-helmrelease-bx-game-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./helm-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: 5-demo-source-helm-git-bx-game-app
  interval: 1m0s
  targetNamespace: 5-demo
  values:
    labels:
      app:
        env: dev
        name: bx-game-app
        version: 7.5.0
    namespace: 5-demo
    replicaCount: 2
    service:
      nodePort: 30005
      type: NodePort
