---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 7-demo-infra-kustomization-oci-dx-game-app-770
  namespace: flux-system
spec:
  dependsOn:
  - name: infra-database-kustomization-git-mysql
  healthChecks:
  - kind: Deployment
    name: block-buster-7-7-0
    namespace: 7-demo
  interval: 10s
  path: ./
  prune: false
  sourceRef:
    kind: OCIRepository
    name: 7-demo-infra-source-oci-dx-game-app-770
  targetNamespace: 7-demo
  timeout: 2m0s
