---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: 7-demo-infra-source-oci-dx-game-app-770
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 7.7.0-14e35a5
  secretRef:
    name: ghcr-secret
  url: oci://ghcr.io/girdhar-singh-rathore/dx-game-app
