---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 8-demo-source-git-bx-game-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: 8-demo
  secretRef:
    name: 8-demo-git-dx-game-app-auth
  url: ssh://git@github.com/girdhar-singh-rathore/dx-game-app.git
