apiVersion: v1
kind: Service
metadata:
  labels:
    app: dx-game-app
  name: dx-game-app-service
  namespace: 1-demo
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30001
  selector:
    app: dx-game-app
    version: 7.1.0
    env: dev
  type: NodePort
